### ISSUE TITLE
Feature: Add extended analysis scanning & chapter thumbnails creation

### ISSUE THREAD

**Issue by Ninjouz** [l3uddz/plex_autoscan#1]
Hey ! Nice script you got there.

Would be nice to have as options : 
- extended analysis scans
- chapter thumbnails creation

That way you could do every thing in one shot before uploading your file to gdrive.

**Comment by l3uddz** [comment]
I'll look into how I can implement this.

**Comment by l3uddz** [comment]
Deep analysis has been implemented for awhile now.

Chapter analysis no plans for this.
