### ISSUE TITLE
401 Unauthorized

### ISSUE THREAD

**Issue by nigelwarning** [l3uddz/plex_autoscan#104]
When I go to the url on my website:

Unauthorized
The server could not verify that you are authorized to access the URL requested. You either supplied the wrong credentials (e.g. a bad password), or your browser doesn't understand how to supply the credentials required.

I get this error. Im running it on a dedicated server.

**Comment by desimaniac** [comment]
https://github.com/l3uddz/plex_autoscan/blob/master/README.md#misc

`"SERVER_ALLOW_MANUAL_SCAN": true,`
