### ISSUE TITLE
TV Metadata is not grabbed when adding files with plex_autoscan. Movies work fine

### ISSUE THREAD

**Issue by samsepiol59** [l3uddz/plex_autoscan#109]
**Describe the bug**
So when a new TV show is added to Plex, it won't match automatically and I'll be left with a blank poster, blank seasons posters, no episodes descriptions, director names, etc - nothing! If I force a "Refresh metadata" (no manual matching, just refresh metadata) on the series though, it finds everything without problems - this has happened with well know series as Futurama, Lost, etc.

When I add a new single episode, it still doesn't grab metadata and the cover image/thumbnail is not the one from TVDb/TMDb!

Movies, on the other hand, match perfectly, without issues and as soon as they're added to Plex!

**To Reproduce**
No way to reproduce it on purpose unfortunately.

**Expected behavior**
Metadata should be automatically grabbed for new episodes, and newly added series should match automatically without having to manually force it via "Refresh metadata" button

**Comment by desimaniac** [comment]
TVDB is currently having issues. This is unrelated to Plex Autoscan.

**Comment by samsepiol59** [comment]
This is related to plex_autoscan because the problem exists even if I use TMDb as my lone agent with TV.

> When I add a new single episode, it still doesn't grab metadata and the cover image/thumbnail is not the one from TVDb/TMDb!

**Comment by desimaniac** [comment]
PAS just tells Plex’s own scanner tool to make the scan. Just a couple days ago, I added a few new shows via PAS and they matched up fine.
