### ISSUE TITLE
which path is which?

### ISSUE THREAD

**Issue by snickers2k** [l3uddz/plex_autoscan#111]
FILE_PATHS vs 
SERVER_FILE_EXIST_PATH_MAPPINGS vs
FILE_EXISTS_TO_REMOTE_MAPPINGS vs
SERVER_PATH_MAPPINGS

could someone please explain these? thanks

**Comment by desimaniac** [comment]
Those settings depend on whether you have Sonarr/Radarr installed on another machine other than Plex and whether they are in a Docker container or not. The readme is detailed. But if you want more help, then you can join the Discord chat server.
