### ISSUE TITLE
Simple Options on top of the file

### ISSUE THREAD

**Issue by snickers2k** [l3uddz/plex_autoscan#112]
Would be great to simply add the own parameters right up top on the config or even a html setup page.
I can't get this to work for 3 Days now. I obviously have no clue really 

Getting this error now:

` 2019-09-07 19:29:14,853 -    ERROR -    GOOGLE [139994569025280]: Exception sending request to https://www.googleapis.com/drive/v3/changes with kwargs={'params': {'pageToken': '837383', 'pageSize': 1000, 'includeRemoved': True, 'includeTeamDriveItems': False, 'supportsTeamDrives': False, 'fields': 'changes(file(md5Checksum,mimeType,modifiedTime,name,parents,teamDriveId,trashed),fileId,removed,teamDrive(id,name),teamDriveId),newStartPageToken,nextPageToken'}}: 
Traceback (most recent call last):
  File "/opt/plex_autoscan/google/drive.py", line 182, in query
    callbacks['data_callback'](resp.json())
  File "/opt/plex_autoscan/google/drive.py", line 602, in _process_changes
    decoded = self.crypt_decoder.decode_path(item_paths[0])
  File "/opt/plex_autoscan/rclone.py", line 28, in decode_path
    decoded = subprocess.check_output([self._binary, "--config", self._config, "cryptdecode", mapped_remote, file_path], stderr=subprocess.STDOUT).rstrip('\n')
TypeError: a bytes-like object is required, not 'str'`

**Comment by desimaniac** [comment]
Need more info. What python version are you using? Have you tried fetching the latest changes from the repo?

**Comment by desimaniac** [comment]
As mentioned in the other issue ticket, youll find better support on the Discord channel.
