### ISSUE TITLE
Some control over log size

### ISSUE THREAD

**Issue by saitoh183** [l3uddz/plex_autoscan#113]
I just wanted to know if it would be possible to add log size control in the config file. The reason behind the request is that Logarr has a hard time loading when the log starts to go over 2mb. Most of my logs in there roll when they hit 1mb just so that logarr stays responsive and more so when loading the page via mobile.

**Comment by zenjabba** [comment]
/var/log/plex_autoscan {
    missingok
    notifempty
    size 2m
    yearly
    create 0600 root root
}

**Comment by saitoh183** [comment]
@zenjabba 

Where do i add that?

**Comment by zenjabba** [comment]
in your logrotate configuration file 

https://www.thegeekstuff.com/2010/07/logrotate-examples/

**Comment by saitoh183** [comment]
@zenjabba Thank you!

**Comment by desimaniac** [comment]
Ill set it to rotate log at 2MB
