### ISSUE TITLE
ModuleNotFoundError: No module named 'pyfiglet

### ISSUE THREAD

**Issue by tamburra** [l3uddz/plex_autoscan#125]
I have just updated to the most recent public release of plex (Version 1.18.2.2029) by recreating the docker container through portioner.  I am using horjulf/plex_autoscan.  Logs are now showing there is an issue and nothing is being scanned anymore.  Below is what i am seeing in my docker logs repeated over and over.

```
# plex_autoscan starting...

Traceback (most recent call last):

  File "/plex_autoscan/scan.py", line 8, in <module>

    from pyfiglet import Figlet

ModuleNotFoundError: No module named 'pyfiglet'

# plex_autoscan waiting for Plex service

# plex_autoscan starting...

Traceback (most recent call last):

  File "/plex_autoscan/scan.py", line 8, in <module>

    from pyfiglet import Figlet

ModuleNotFoundError: No module named 'pyfiglet'

# plex_autoscan waiting for Plex service
```

**Comment by desimaniac** [comment]
Install the dependencies in requirements.txt
