### ISSUE TITLE
ImportError: cannot import name 'DeleteQuery'

### ISSUE THREAD

**Issue by jaketame** [l3uddz/plex_autoscan#15]
Looks like peewee on py is now version 3.0 thus I'm getting the below errorr

Traceback (most recent call last):
  File "/opt/apps/autoscan/scan.py", line 62, in <module>
    import db
  File "/opt/apps/autoscan/db.py", line 4, in <module>
    from peewee import DeleteQuery
ImportError: cannot import name 'DeleteQuery'

**Comment by l3uddz** [comment]
Will take a look at this.
In the meantime you should be-able to downgrade relatively painlessly by running ```sudo python -m pip install -r requirements.txt```
The requirements.txt specifies 2.10.1
