### ISSUE TITLE
Ubuntu 16.04 server OK, Ubuntu Desktop 18.04 dont work?

### ISSUE THREAD

**Issue by MorphyDK** [l3uddz/plex_autoscan#150]
Hi

Im using this great piece of software on my Ubuntu server 16.04, works perfectly. Detecting and updating everything I throw at the server . :)
The logs looks like this: 

#########################################################################
# Author:   l3uddz                                                      #
# URL:      https://github.com/l3uddz/plex_autoscan                     #
# --                                                                    #
# Part of the Cloudbox project: https://cloudbox.works                  #
#########################################################################
# GNU General Public License v3.0                                       #
#########################################################################

 2020-05-26 18:21:32,642 -     INFO -  AUTOSCAN [XXXXXXXXXXXXXXX]: Starting server: http://0.0.0.0:3467/XXXXXXXXXXXXXXXXXXXXXXXXXXX

So far so good :)

I have aquired an Intel NUC, install Ubuntu Desktop 18.04 on it , made a plex server etc.
I have installed your plugin as same on the server, same user etc.

The problems I encountered is when running python scan.py sections , I see its finding the sections from my server. But when I look in config.json its missing section ( also after a complete server scan )
This is missing : 
 "PLEX_SECTION_PATH_MAPPINGS": and then all the sections it just found. 

Nothing is added to the file.
If I try manually adding the sections to the file, it still dont work.

Log from systemctl status plex_autoscan.service: 

Jun 17 09:08:44 plex-NUC8i3BEH scan.py[5666]: #         Part of the Cloudbox project: https://cloudbox.works          #
Jun 17 09:08:44 plex-NUC8i3BEH scan.py[5666]: #########################################################################
Jun 17 09:08:44 plex-NUC8i3BEH scan.py[5666]: #                   GNU General Public License v3.0                     #
Jun 17 09:08:44 plex-NUC8i3BEH scan.py[5666]: #########################################################################
Jun 17 09:08:44 plex-NUC8i3BEH scan.py[5666]:  2020-06-17 09:08:44,696 -     INFO -  AUTOSCAN [xxxxxxxxxxxxxxxx]: Starting server: http://0.0.0.0:3467/xxxxxxxxxxxxxxxxxxxxxxxxxxxx
Jun 17 09:08:44 plex-NUC8i3BEH scan.py[5666]:   Serving Flask app "scan" (lazy loading)
Jun 17 09:08:44 plex-NUC8i3BEH scan.py[5666]:  * Environment: production
Jun 17 09:08:44 plex-NUC8i3BEH scan.py[5666]:    WARNING: This is a development server. Do not use it in a production deployment.
Jun 17 09:08:44 plex-NUC8i3BEH scan.py[5666]:    Use a production WSGI server instead.
Jun 17 09:08:44 plex-NUC8i3BEH scan.py[5666]:  * Debug mode: off

Is this not supported for Desktop versions? Or am I simply missing a setting somewhere?

Thanks :)

**Comment by saltydk** [comment]
python scan.py sections, does not add entries to the config.
