### ISSUE TITLE
Docker unhealthy 

### ISSUE THREAD

**Issue by nickmers** [l3uddz/plex_autoscan#152]
Since yesterday, dont work for me. I didnt do nothig but i dont know what happen.

![Screenshot_1](https://user-images.githubusercontent.com/52675796/88383462-d8950280-cdaa-11ea-8b33-9fedf854a944.png)
![Screenshot_3](https://user-images.githubusercontent.com/52675796/88383464-d92d9900-cdaa-11ea-8c0d-8b891fb63c75.png)

**Comment by bad1dea** [comment]
You have an error with your config, mainly Rclone portion.

**Comment by saltydk** [comment]
This repo does not maintain a container.
