### ISSUE TITLE
Problem PlexAutoscan

### ISSUE THREAD

**Issue by freedom1701** [l3uddz/plex_autoscan#174]
Hello
When installing plex autoscan, I try to activate plex autoscan on google by typing this command:
/opt/plex_autoscan/scan.py authorize
Here is the error it gives me:

seed@Ubuntu-1804-bionic-64-minimal:~$ /opt/plex_autoscan/scan.py authorize
Traceback (most recent call last):
  File "/opt/plex_autoscan/scan.py", line 8, in <module>
    from pyfiglet import Figlet
ModuleNotFoundError: No module named 'pyfiglet'

Thanks for your help

**Comment by Horribleness** [comment]
Make sure you install the PIP requirements. 

`sudo -H pip3 install -r /opt/plex_autoscan/requirements.txt`
