### ISSUE TITLE
Lidarr support?

### ISSUE THREAD

**Issue by samwiseg00** [l3uddz/plex_autoscan#18]
Any chance you could add support for Lidarr? https://github.com/lidarr/Lidarr

Current error
```
2018-03-03 16:37:07,409 -    ERROR -  AUTOSCAN [ 6921]: Unknown scan request from: '1.1.1.1'
```

**Comment by l3uddz** [comment]
Yep, will look to get that added tonight

**Comment by l3uddz** [comment]
added

**Comment by samwiseg00** [comment]
Thanks!!! wow that was fast! My first test was successful.. I will let you know if i run into any issues... thanks again!

**Comment by samwiseg00** [comment]
I spoke too soon... it does not work on rename :(

**Comment by l3uddz** [comment]
The issue with rename is due to sonarr/radarr/lidarr not sending the path of the file that was renamed. If it sends this info in the webhook I will beable to make it work with renames instead of just download/upgrades.

**Comment by samwiseg00** [comment]
ah ok thanks!
