### ISSUE TITLE
Integration with Watcher

### ISSUE THREAD

**Issue by jaketame** [l3uddz/plex_autoscan#2]
A few of us are using Watcher3, it would be good to see this implemented for that too.

https://github.com/nosmokingbandit/Watcher3

Happy to assist where I can but still reading your code to understand it.

Cheers

**Comment by l3uddz** [comment]
I'll certainly take a look. If watcher3 is able to send a webhook (POST request) on import that includes the full file path, then im fairly certain it could be made to work. Even if it can launch a custom script, you could simply enable SERVER_ALLOW_MANUAL_SCAN you should beable to fire off a POST request like so:

curl -d "eventType=Manual&filepath=/mnt/unionfs/Media/Movies/Shut In (20166f533t In (2016) - Bluray-1080p.x264.DTS-GECKOS.mkv" http://localhost:3468/0c1fa3c9867e48b1bb3aa055cb86

Obviously you would replace the filepath / server ip or hostname / server_pass on the end

**Comment by l3uddz** [comment]
After taking a very brief look at their wiki, i cant see anything about webhooks (unless I overlooked it). However they do support post processing scripts, so you could simply write a small plugin that sends a POST request with the above fields using argument 7 supplied by watcher3. something like:

```python
import requests
import sys

if __name__ == "__main__":
	try:
		file = sys.argv[7]
		if file is None:
			print("The New File supplied by Watcher3 was None...")
			exit(1)
		payload = {'eventType': 'Manual', 'filepath': file}
		requests.post('PLEX_AUTOSCAN_URL', data=payload)
	except Exception as ex:
		print("There was an exception while processing the scan request from Watcher3: ", ex)
	exit(0)
```
