### ISSUE TITLE
Description Metadata?

### ISSUE THREAD

**Issue by bassrock** [l3uddz/plex_autoscan#3]
I used plex autoscan for a test run on a few episodes. For the few episodes I tried it on the description and episode title have never loaded and I can not get it to load.

Is this expected behavior?

**Comment by l3uddz** [comment]
That does not sound normal behaviour. The title and description should load if it's available. The only thing that sometimes doesn't load seems to be an episode preview thumbnail. 

What do you see in the log file when it starts a scan?

**Comment by bassrock** [comment]
What logs would be most useful. Also the the episodes it was used on still wont load their metadata even with a normal scan in plex. (i have disabled plex autoscan for now)

**Comment by l3uddz** [comment]
Sounds like a permission issue. plex_autoscan logs from the time it received the scan request to the Finished scan message would be helpful. 

Would be helpful to see the scan command it used. Am I correct in thinking its using the normal plex user for plexmediaserver?

**Comment by bassrock** [comment]
Hmm was supposed to be. Its possible it was a permission issue. Going to try again on episodes tonight properly.

**Comment by bassrock** [comment]
Happened again. Running as the Plex User: 

<img width="1469" alt="screen shot 2017-10-11 at 5 38 49 pm" src="https://user-images.githubusercontent.com/1010384/31473719-2e0fd702-aeab-11e7-8e40-f4522f157910.png">

**Comment by bassrock** [comment]
nvm looks to be working. Will reopen if I see it again.

**Comment by samsepiol59** [comment]
Did you ever have this problem again?! I can't seem to grab metadata for TV shows with autoscan, but it works perfectly with movies!
