### ISSUE TITLE
possible to use without Radarr/Sonarr?

### ISSUE THREAD

**Issue by chienb** [l3uddz/plex_autoscan#33]
I don't use either services so I was wondering if plex_autoscan would work without them? Is it possible to use an external service to send a POST request to trigger a scan?

**Comment by l3uddz** [comment]
If you turn SERVER_ALLOW_MANUAL_SCAN on, you can trigger scans with: 


```
curl -d "eventType=Manual&filepath=/mnt/unionfs/Media/Movies/Shut In (20166f533t In (2016) - Bluray-1080p.x264.DTS-GECKOS.mkv" http://localhost:3468/0c1fa3c9867e48b1bb3aa055cb86
```

**Comment by desimaniac** [comment]
More info on that [here](https://github.com/l3uddz/plex_autoscan#misc).
