### ISSUE TITLE
SERVER_USE_SQLITE WIKI/Explenation

### ISSUE THREAD

**Issue by Mirabis** [l3uddz/plex_autoscan#34]
Hi,

Could you explain the purpose of the "SERVER_USE_SQLITE" option? I've been using this script on Windows so my Plex VM will issue a scan on a specific folder after import... because media is on my Hypervisor & downloads come from another VM.

However... I'm trying to speed up the scan process and was wondering what the SERVER_USE_SQLITE option does.

**Comment by desimaniac** [comment]
It merges multiple requests to the same parent folder (eg requests after consecutive episodes downloaded), into one scan request.
