### ISSUE TITLE
Deletion Support

### ISSUE THREAD

**Issue by camjac251** [l3uddz/plex_autoscan#39]
I noticed that if I delete something on Sonarr/Radarr, Plex won't see that it's been deleted. Would this be possible? I think a few others like renames also didn't work for me either with it sending to plex right away.

**Comment by daniel-loader** [comment]
This would be great yeah, often I upgrade and it leaves multiple copies on plex but sonarr has deleted the older lower quality version and it's only picked up later by a global scan + trash delete.

**Comment by l3uddz** [comment]
Renames should work. Deletions will need to look into.
