### ISSUE TITLE
No episode artwork

### ISSUE THREAD

**Issue by canonlp** [l3uddz/plex_autoscan#4]
With my plex_autoscan, it currently doesn't get any episode image. If it does, it's usually the season artwork instead of episode artwork. It's scraping metadata just fine, but I'm just not getting the image.

**Comment by l3uddz** [comment]
Were you using this before? If so, was this working fine? I have been using it for awhile and this is the first time I have noticed this problem, which makes me believe something changed with plex. Im looking into ways to solve this but really it seems as if its a plex issue.

Especially considering the fact we see things such as returned via the CLI scanner:

```
2017-10-12 17:18:22,951 -     INFO -     UTILS [24574]: GUI: Background media analysis on Star S02 E01
```

This is what makes me think its an issue with plex.

**Comment by canonlp** [comment]
Yes I was using this before. I imported a lot of tv shows before and they were fine. These past 5 imports though, they had nothing. I just checked TVDB, and it looks like 4 of those episodes don't have an image yet, so that would explain why? One of them definitely has an image, but it's not updating my metadata though.

**Comment by l3uddz** [comment]
I was under the impression it would generate a thumbnail when performing background media analysis, which if im correct, it always did. But something changed lately with plex. Im looking at a way to solve it but it will really be a bandaid until plex fix the cause of it.

**Comment by canonlp** [comment]
Still happening with my new shows. If I add an old show that has a picture on tvdb, it's fine, since it just uses that. The problem seems to derive from the image not being on tvdb? So it's not generating the thumbnail with the use of plexdrive perhaps?

**Comment by l3uddz** [comment]
Try the queuemanager branch. It analyzes items now and has a small db of files to be scanned. Make sure you install peewee ```sudo python -m pip install peewee```.
You need to turn the sqlite option on in config and make sure Plex URL and token and database are set correctly.

**Comment by l3uddz** [comment]
Assuming this is solved with the analyze episode file capability that was added since this issue.
Let me know if its not.
