### ISSUE TITLE
Integration with sickbeard_mp4_automator

### ISSUE THREAD

**Issue by andrewkhunn** [l3uddz/plex_autoscan#42]
I see there's a closed issue where you offered a barebones Watcher post-processing script to manually call plex_autoscan and I was wondering if it might be possible to get an example for [sickbeard_mp4_automator](https://github.com/mdhiggins/sickbeard_mp4_automator)?

I'd really like to disable their built-in Plex update mechanism as it triggers a full library rescan.

Thanks for any help you can offer!

**Comment by desimaniac** [comment]
There you can send manual scan requests via curl commands. See [here](https://github.com/l3uddz/plex_autoscan#misc).

**Comment by andrewkhunn** [comment]
I managed to get the author of sickbeard_mp4_automator to help me crib together a script. Just leaving this here for future reference to anyone interested. This will call plex_autoscan after sickbeard_mp4_automator is done converting the file:

```
#!/usr/bin/python
import os
import json
import requests

def main():
	print("Plex Autoscan Post Script")
	url = "http://localhost:3689/apikey"

	files = json.loads(os.environ.get('MH_FILES'))
	if not (files):
        print("Error - Did not find environment variables.")
        return

	for filename in files:
		dirname = os.path.dirname(filename)
		payload = {'eventType': 'Manual'
				   'filepath': dirname}
		try:
			requests.post(url, json=payload)
		except Exception as e:
			print("Error - Request failed")
			print(e)

if __name__ == "__main__":
    main()
```

**Comment by andrewkhunn** [comment]
I managed to get the author of sickbeard_mp4_automator to help me crib together a script. Just leaving this here for future reference to anyone interested. This will call plex_autoscan after sickbeard_mp4_automator is done converting the file:

```
#!/usr/bin/python
import os
import json
import requests

def main():
  print("plex_autoscan Post-processing Script")
  url = "PLEX_AUTOSCAN_URL"

  files = json.loads(os.environ.get('MH_FILES'))
  if not (files):
    print("Error - Did not find environment variables.")
    return

  for filename in files:
    dirname = os.path.dirname(filename)
    payload = {'eventType': 'Manual', 'filepath': dirname}
    try:
      requests.post(url, json=payload)
    except Exception as e:
      print("Error - Request failed")
      print(e)

if __name__ == "__main__":
  main()
```
