### ISSUE TITLE
Feature: Multiple servers to connect to?

### ISSUE THREAD

**Issue by danielloader** [l3uddz/plex_autoscan#44]
I've recently started running plex on a VPS as well as at home, both backed by google drive storage with the home instance being reserved for my own use.

Would it be possible to get autoscan to trigger onto multiple servers?

**Comment by desimaniac** [comment]
Plex Autoscan is meant to be installed on the same server as Plex Media Server. If you have more than one PMS installed on separate boxes, you can simply install PAS there as well and have Sonarr/Radarr send 2 webhook requests.
