### ISSUE TITLE
Feature: add variable for duration between file checks

### ISSUE THREAD

**Issue by jusher00** [l3uddz/plex_autoscan#49]
First of all: Great little tool!! I only discovered it a couple of days ago and already love it!

There's only one small problem I have with it. I have two different servers, one for uploading to my drive, and one for PMS. So PMS only sees the files once actually uploaded to the drive, which is, in case of very large files, substantially later than after Sonarr/Radarr calls the webhook. I increased the `SERVER_SCAN_DELAY` to 1 hour, but even that is not enough for large files. What I would like to see is an option `SERVER_FILE_CHECK_DELAY`, which is applied as a delay between the file checks, instead of the one minute default. That way, I could decrease my `SERVER_SCAN_DELAY` to something like 15 minutes, which is perfect for TV episodes, and in case of a 4K movie, the much increased `SERVER_FILE_CHECK_DELAY` would check the drive until it finally appears.

I hope that this is not too hard to implement! Keep up the great work!!

**Comment by desimaniac** [comment]
You could 1) mount your uploading box to your PMS one as a unionfs type drive to have it scanned while it’s local. It’s how Cloudbox is handling it with a Feeder/Media box setup, and 2) you can enable Google Drive monitoring, which will add requests for files that were missed. See the readme page for details.

**Comment by jusher00** [comment]
1) That's not an option for me, unfortunately. As both servers are remote, I would not want to work with NFS due to security concerns. On top of that it would further increase the complexity of my setup and, due to the physical separation of the servers, lead to more lag when mounted as a UnionFS. Also, I had some problems with UnionFS when I used it a few months back, so if possible, I'd like to avoid using it altogether.

2) That sounds like the much better workaround, I'll look into that. However, it's still in beta and I'd much prefer a variable for the delay between file checks.

**Comment by desimaniac** [comment]
That needs to be updated. It’s been working really well for quite a large group of people since that note was added to the readme.

**Comment by desimaniac** [comment]
Still ould be a useful addition, nonetheless. It may be a little while to have it tested and approved, if that’s ok.

**Comment by jusher00** [comment]
Not a problem!
