### ISSUE TITLE
Escape special characters in filenames

### ISSUE THREAD

**Issue by canonlp** [l3uddz/plex_autoscan#5]
Just noticed a bug - when there are special characters in the path, it doesn't parse the file correctly.

```
2017-10-13 04:01:59,445 -    DEBUG -  AUTOSCAN [ 1418]: Client '64.137.231.4' request dump:
{
    ".Link's.Buddy.System-S01E02-Super.Special.Secret.Bike.WEBDL-1080p.mkv": "",
    ".Link's.Buddy.System/Season_01/Rhett.": "",
    "eventType": "Manual",
    "filepath": "/mnt/plexdrive/TV/Rhett."
}
```
Note the file path is supposed to be `/mnt/plexdrive/TV/Rhett.&.Link's.Buddy.System/Season_01/Rhett.&.Link's.Buddy.System-S01E02-Super.Special.Secret.Bike.WEBDL-1080p.mkv`

**Comment by l3uddz** [comment]
I advise to enable Replace Illegal Characters inside sonarr and radarr.

https://i.imgur.com/70pzIAV.png

The parsing is happening by flask so is outside of my control.

**Comment by canonlp** [comment]
Yes, I actually have that ticked. But it didn't replace it?
