### ISSUE TITLE
Extend rclone rc to include cache/fetch 

### ISSUE THREAD

**Issue by danielloader** [l3uddz/plex_autoscan#53]
So rclone has recently implemented https://rclone.org/rc/#cache-fetch-fetch-file-chunks so you can pre-warm the cache, would it be worth an optional config section to be able to warm up x amount of chunks at scan time? 

I know plex scanning the file will read a set amount of the video file to get media stats, but it'd be nice to be able to preload say 100MB or 1GB etc.

**Comment by desimaniac** [comment]
Do you have an example RC command? And how many chunks at the start and/or end of the file would be wanted?

**Comment by danielloader** [comment]
I'll close this as for my personal use I've removed the cache layer and rely on VFS caching for rewinding. Didn't see the trade off benefits to storing chunks locally vs not, only worked well if a new file came out and multiple people were watching it at the same time but I've mitigated that by using mergerfs to keep a local cache of the last 7 days of files.
