### ISSUE TITLE
FEATURE: Crypt Support for Google Drive Monitoring

### ISSUE THREAD

**Issue by m1lkman** [l3uddz/plex_autoscan#62]
Any chance you're working on Google Drive Monitoring rclone crypt support for those of us hosting PMS instances sperate from our sonarr/radarr setups? I saw the below thread and it seems it may be in the works. Just looking for a status or feature thread I can follow. Thank you.

https://forum.rclone.org/t/mount-events-api/7095

**Comment by l3uddz** [comment]
No plans at the moment for this.

However it would be possible by using the Rclone function to decrypt encrypted paths.

**Comment by m1lkman** [comment]
This would be key for me (and those of use using encryption) to take advantage of autoscan and your Feederbox/Mediabox solution.

**Comment by clg27** [comment]
So I’ve been working on this for the past few nights and I think I have it figured out. Check out my fork here:  https://github.com/clg27/plex_autoscan The important settings that you need to configure are explained in the Rclone Crypt Monitoring section. I think it explains everything fairly well, but if you run into problems configuring it let me know.

I’ve only been using it for about a day but it seems to be working great for me. So feel free to test it out and let me know if you run into any problems and I’ll try to help you.

If other people want to test this out too it would be great. Then once I’m confident that it works well I’ll put in a pull request to get it merged into the main plex_autoscan.

There is also a discussion on the rclone forum located here: https://forum.rclone.org/t/google-drive-mount-monitoring-with-crypt/9822

**Comment by m1lkman** [comment]
Thanks @clg27, I will set this up tomorrow morning and let you know how it goes.

**Comment by m1lkman** [comment]
When I run the initial "python scan.py sections" I get the below but when I run it from the original plex_autoscan it works.

```
Traceback (most recent call last):
  File "scan.py", line 16, in <module>
    import config
  File "/opt/plex_autoscan/config.py", line 22, in <module>
    class Config(object):
  File "/opt/plex_autoscan/config.py", line 63, in Config
    'ENABLED': false,
NameError: name 'false' is not defined
```

**Comment by clg27** [comment]
Sorry, I didn't actually test the config generator because I already had a working config.
I think I fixed it so you can try pulling the new version. I'm on my phone though so if it doesn't work you'll have to wait until I can look at it later tonight.

**Comment by m1lkman** [comment]
I figured out that error above and sent you a pull request with the fix. Simple case typo. Running now. I'll let you know how it goes.

**Comment by m1lkman** [comment]
This looks to be working great. Took me a little to get it dialed in. Thank you @clg27.

**Comment by clg27** [comment]
@m1lkman did you run into any other problems while setting it up? Or do you have any changes to the documentation that might make it easier?

**Comment by m1lkman** [comment]
@clg27 I think it looks good. I had never set up autoscan at all before so there was a learning curve. It would be nice if config.py did more automatically to pull libraries (paths and section IDs) and other values were auto-populated but that's for another day. Thank you for working this out. The performance is so much better than keeping track of everything that's uploaded on every plex instance I have running outside of my feeder box. Now if we can get this merged with everything in cloudbox :).

**Comment by clg27** [comment]
Glad it works for you. 

Running scan.py sections should populate some section IDs but I can't remember what exactly it populates. 

@l3uddz it looks like I've completed this feature request. I'll put in a pull request so you can take a look at it.

**Comment by m1lkman** [comment]
@clg27 I noticed that it's failing to import movies or files updated in my movies folder. Television works fine. Here's what the autoscan log shows

```
2019-05-10 07:03:38,851 -     INFO -  AUTOSCAN [139796973319936]: There's 2 Google Drive change(s) to process
 2019-05-10 07:03:38,916 -    ERROR -     UTILS [139796973319936]: Rclone could not decode filename 'm36m9b347ct895kj3maq38pus/j0djf6qnp5decd2f79u38vhlno2jfgfmrc3msstonaoo1cbluqmg/8o1da1cmlhqtebedl93iucvfluj8g2jopcc5vjkljtri5fk0u9tl6m88smdtlh467neu2tfg1cofq7jqc8bs7ppusf1j0dmcg2l9b2jmd8sfgtigtta7cid06q53g7rt3mln1mve58eslh4kdta7i1maeo10k9dla6ovljd26jjor51n7ir4pc2e48ghc6fkpajpdttqatg1e'
 2019-05-10 07:03:38,964 -     INFO -  AUTOSCAN [139796973319936]: Ignored 2 file(s) from Google Drive changes for disallowed file extensions
```

Paths seem to be configured correctly in the config file. The only difference is my Movies folders are one folder depth less deep that my television folders because of no seasons folders i.e. Movies\Move name\movie file.mkv vs Television\Series name\season number\television file.mkv.

this is the file that was added

```
Movies/***Redacted*** (2019)/***Redacted*** (2019) WEBDL-1080p x264 EAC3 [EN+AR+CS+DA+DE+EL+ES+FI+FR+HE+HU+ID+IT+JA+KO+Norwegian Bokmal+NL+PL+PT+RO+RU+SV].mkv
```

Any ideas?

**Comment by desimaniac** [comment]
@clg27 Really wish the PR was pointed at develop branch since there were updates to the Google Drive Monitoring section in config. Also there is another PR for this, could either one of you check that out?

**Comment by m1lkman** [comment]
I'd be glad to test it out, can you break down these values for the new RCLONE section. It's a bit different than the RCLONE_CRYPT section @clg27 put together. Here's as far as I got with it.

```
  "RCLONE": {
    "RCLONE_RC_CACHE_EXPIRE": {
      "ENABLED": true,
      "FILE_EXISTS_TO_REMOTE_MAPPINGS": {
        ".config": [
          "/home/plex/media/.config/"
        ]
      },
      "RC_URL": "http://localhost:5572"
    },
    "BINARY": "/usr/bin/rclone",
    "CONFIG": "/home/plex/.config/rclone/rclone.conf",
    "CRYPT_MAPPING": {
      "My Drive/encrypt/": [
        "gcrypt:"
      ]
    }
  }
```

**Comment by clg27** [comment]
@m1lkman I'll take a look at that this weekend. You could also try the other method from PR #92. I think it might be more robust compared to my solution. 
@desimaniac check out the other PR as well, it points to the develop branch. I didn't realize there was one guy I could probably get my method working with the develop branch.

**Comment by clg27** [comment]
Ok, so I've been playing around with some things this afternoon. I think the easiest way to implement rclone crypt is using @daghaian's work that goes with PR #92. This works with the new google drive code and supports multiple rclone remotes.

However, I had to make some changes to the rclone.py file to get it to work with my specific situation. Also before that PR is merged, I think there needs to be a few things done that I've listed on the PR.

I've closed my PR and suggest that we continue working on @daghaian's.

**Comment by m1lkman** [comment]
@l3uddz I think this is working well now in my [PR](https://github.com/daghaian/plex_autoscan/pull/1) that @clg27 and I worked through along with @daghaian's original code. What are next steps? Do you need me to do any testing or other validation?

**Comment by m1lkman** [comment]
@clg27 have some time to try out the latest PR with your crypt setup? Looking for some additional testers and feedback. Thanks.

**Comment by clg27** [comment]
I will try to test this out this weekend. I assume that if it's working for you with a crypt subfolder, I should have no problems with my setup.

**Comment by clg27** [comment]
@m1lkman it's working great for me.  I skimmed PR98 and I think everything is included. @desimaniac I think this can be merged in to the main repo.

**Comment by desimaniac** [comment]
Added in https://github.com/l3uddz/plex_autoscan/commit/7a25cdedf27bcd7dc9e7573fb59351fdf85f4646

**Comment by gurabli** [comment]
@m1lkman I have some problems setting up crypt mappig (or something else). Do you mind helpming me out?

**Comment by m1lkman** [comment]
@gurabli what do you have so far? Where're your encrypted files? My Drive or Shared Drive? What's your crypt mount name?

**Comment by gurabli** [comment]
> @gurabli what do you have so far? Where're your encrypted files? My Drive or Shared Drive? What's your crypt mount name?

Many thanks for getting back on this!
I use Shared Drives. PlexAutoscan is running in docker.

This is my config.json now: [LINK](https://pastebin.com/hLCza8m3)
And this is the rclone.conf: [LINK](https://pastebin.com/hmm6jzY5)

**Comment by m1lkman** [comment]
> Many thanks for getting back on this!
> I use Shared Drives. PlexAutoscan is running in docker.
> SharedDrive name: frakk
> 
> This is my config.json now: [LINK](https://pastebin.com/hLCza8m3)
> And this is the rclone.conf: [LINK](https://pastebin.com/hmm6jzY5)

I'm assuming frakk is the name of the shared drive and encrypt is the name of the folder in that drive? looks correct to me if these statements are true. Maybe a docker issue? I've never set up PAS in docker. What's the actual problem? Errors? Logs?

**Comment by gurabli** [comment]
> > Many thanks for getting back on this!
> > I use Shared Drives. PlexAutoscan is running in docker.
> > SharedDrive name: frakk
> > This is my config.json now: [LINK](https://pastebin.com/hLCza8m3)
> > And this is the rclone.conf: [LINK](https://pastebin.com/hmm6jzY5)
> 
> I'm assuming frakk is the name of the shared drive and encrypt is the name of the folder in that drive? looks correct to me if these statements are true. Maybe a docker issue? I've never set up PAS in docker. What's the actual problem? Errors? Logs?

Well, I have the paths as in rclone.conf I can't check it, as I don't see it in G Drive web, just encrypted files.
The paths are as in the config file. 
How do I set logging to more detailed? As with this config I just get like 2 changes detected, ignoring 1. But not added to Plex. 
Using Plex webhooks works fine.

**Comment by gurabli** [comment]
Update: I managed to turn on debug logging and based on these information I also managed to configure. Now it is working perfeclty.

For Shared Drives the Crypt Mapping should be: "tcrypt" and not "gcrypt". 
And I had wrongly configured FILE_PATHS. It should be the "TDRIVE_NAME/PATH"

Btw, what is the recommended poll interval setting? I have it at 90 now.
