### ISSUE TITLE
Can't run script

### ISSUE THREAD

**Issue by antigravity83** [l3uddz/plex_autoscan#68]
Hi there

Getting this error when attempting to run the script as per the readme

```
● plex_autoscan.service - Plex Autoscan
   Loaded: loaded (/etc/systemd/system/plex_autoscan.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Wed 2018-12-12 20:23:20 AEST; 1s ago
  Process: 30554 ExecStart=/opt/plex_autoscan/scan.py server --loglevel=INFO (code=exited, status=1/FAILURE)
 Main PID: 30554 (code=exited, status=1/FAILURE)

Dec 12 20:23:20 FlixNow1 systemd[1]: plex_autoscan.service: Unit entered failed state.
Dec 12 20:23:20 FlixNow1 systemd[1]: plex_autoscan.service: Failed with result 'exit-code'.
```

Unfortunately there's not a lot to go on - any help would be great.

**Comment by desimaniac** [comment]
Did you fill in your username and group in the service file?

**Comment by antigravity83** [comment]
> Did you fill in your username and group in the service file?

Yes - I currently have user=root

I also tried:

user=plex
group=plex

**Comment by antigravity83** [comment]
Ahh. Fixed it. I wasn't using a \\ when referencing a file location with spaces in the name. I was using a single \
