### ISSUE TITLE
Cant connect to local ip

### ISSUE THREAD

**Issue by 3daystoday** [l3uddz/plex_autoscan#69]
I can just connect to plex_autoscan server with my external ip, I like to have all ports closed on the server for some extra security,

Is this a known issue or just me having troubles?

**Comment by animosity22** [comment]
I'd say you don't have the ports closed if you can connect to it externally.

If you want to change the IP so it only listens on localhost, you'd change this line in the config

  "SERVER_IP": "0.0.0.0",

to 

  "SERVER_IP": "127.0;0.1,

**Comment by 3daystoday** [comment]
I had to use my local docker IP network range. Even tough I dont runt this in docker.

So now everything works and I can keep my ports closed. :)
