### ISSUE TITLE
PLEX_ANALYZE_DIRECTORY not turning off

### ISSUE THREAD

**Issue by jaredneedell** [l3uddz/plex_autoscan#71]
I have PLEX_ANALYZE_DIRECTORY set to false yet the Plex_Autoscan is still doing an analysis of all the files in the season folders. This is causing my google drive to get banned when I'm updating 3-4 different tv series with one episode.

Here's a snippet of config.json on my server

`"PLEX_ANALYZE_DIRECTORY": false,
  "PLEX_ANALYZE_TYPE": "basic",
  "PLEX_DATABASE_PATH": "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-in Support/Databases/com.plexapp.plugins.library.db",
  "PLEX_EMPTY_TRASH": false,
  "PLEX_EMPTY_TRASH_CONTROL_FILES": [
    "/mnt/unionfs/mounted.bin"
  ],`

**Comment by desimaniac** [comment]
That option only toggles between folder specific and file specific anaylis. 

What you are looking for is `PLEX_ANALYZE_TYPE`. If you set that to `off`, it will disable analysis period.

**Comment by desimaniac** [comment]
Also would like to mention, I'm using Plexdrive 5 with analysis enabled, and experience no Google Drive bans.

**Comment by jaredneedell** [comment]
Thanks, @desimaniac, I'm looking to just analyze just the file, with directory set to false, it's still scanning all the directories in the parent folder.
