### ISSUE TITLE
Remote PMS for Windows Configuration Possible?

### ISSUE THREAD

**Issue by BzowK** [l3uddz/plex_autoscan#72]
Hey - 

I ran across your scripts today when looking for a solution your project seems to resolve.  Currently, I'm using a PowerShell script I wrote within Sonarr, but can't get it to work 100% of the time.

Although a frequent Linux user, I have my Plex Server installed on Windows Server 2016.  In addition, the source path for each of its many libraries use drives mapped to a SMB path on a different Windows system which hosts a 43.5tb disk pool.

With that being said, I have a couple of questions, please...
1. I was planning to install your scripts on one of my Ubuntu servers, but when configuring, I hit a roadblock.  Is not it possible to use your current scripts with a Windows-based PMS and/or library source paths located on a Windows system?
2. If I had PMS on Linux, it seems your scripts must be installed to either the same Linux system running PMS or a Docker container running PMS.  Is this correct or could a Linux system remote to where your scripts are installed could be used?

Thank You!

**Comment by desimaniac** [comment]
It can work on a windows vps (tested this before), you just need the python requirements. Checkout the old readme file on the repo. 

This is meant to be installed on the same system as where PMS is since it relies on PMS scanner’s CLI tool.
