### ISSUE TITLE
Error while loading shared libraries: libva.so.2

### ISSUE THREAD

**Issue by 3daystoday** [l3uddz/plex_autoscan#76]
So the scripts runs fine, but I get this error:

2019-02-08 11:06:51,045 -     INFO -     UTILS [140284330137344]: /usr/lib/plexmediaserver/Plex Media Scanner: error while loading shared libraries: libva.so.2: cannot open shared object file: No such file or directory

Seems it cant trigger the scanner looks like it's all good in plex_autoscanner but the scanner is never triggerd in PLEX, this is on a existing install wich used to run fine with no changes.

Anyone experiencing the same, or got a solution?

**Comment by jalmansor** [comment]
The library path changed in the latest PMS beta release to `/usr/lib/plexmediaserver/lib`, which you'll need to update in your plex_autoscan config.json.

**Comment by jalmansor** [comment]
Just ran into it myself and took me a minute to realize they just moved all those libs into their own folder.

**Comment by 3daystoday** [comment]
hrm, so in my current config i've got:

 "PLEX_SCANNER": "/usr/lib/plexmediaserver/Plex\\ Media\\ Scanner",

What should that be changed to?

**Comment by Migz93** [comment]
Change `PLEX_LD_LIBRARY_PATH` to have `/lib` on the end, it should look like this
`"PLEX_LD_LIBRARY_PATH": "/usr/lib/plexmediaserver/lib",`

Make sure you restart the plex_autoscan service afterwards, no need to change the "PLEX_SCANNER" line.

**Comment by 3daystoday** [comment]
Ah, running plex in a docker, so plex autoscan cant see that folder at all atm. Havet to figure that out first :)

Sorry for all the questions, but do you have any idea how?

**Comment by Migz93** [comment]
I also run plex in a docker?
Just change the line in your plex_autoscan config file to the above and then restart plex_autoscan service.

**Comment by 3daystoday** [comment]
Sorry, it's working now, looked to quick on the log file.

The file scans in fine now, but just as before I get this error, dont know if i should bother since the file accualy scans in fine.

 2019-02-08 13:39:38,320 -    ERROR -      PLEX [140155843659520]: Could not locate record in media_parts where file = '/mnt/unionfs/tv/HD TV/Star Trek- Discovery/Se                                                                       ason 2/Star Trek- Discovery - S02E04 - An Obol for Charon WEBDL-1080p.mkv', 1/5 attempts...    

x5 times

Thanks for the help :)

**Comment by danjames92** [comment]
Bad path mappings have nothing to do with the scanner working. Fix your setup and it'll work.

**Comment by Migz93** [comment]
The latest version of Plex changed the library paths which will break everyones PAS config, which was the initial problem.

The second one of "Could not locate record in media_parts" is indeed most likely related to bad path mappings.

**Comment by a925sw** [comment]
After the recent PMS update, I too started to get the media_parts error. As far as I can tell, none of my path mappings are an issue. I just thought I'd chime in, I am looking into the issue. I will report in when/if I find a reason.

**Comment by randyjc** [comment]
change in your config the following:
from ` "PLEX_LD_LIBRARY_PATH": "/usr/lib/plexmediaserver", `
to ` "PLEX_LD_LIBRARY_PATH": "/usr/lib/plexmediaserver/lib", `

after that it works again.

**Comment by randyjc** [comment]
Oh my bad, saw that Migz already mentioned that.

**Comment by a925sw** [comment]
I had already applied the remedy. The issue persisted after changing the location and is why I was mentioning.. I believe that's what 3daystoday was saying was happening for him as well. I ended up wiping out my .db/token mostly because I had other reasons to do so and just let it start fresh.

**Comment by desimaniac** [comment]
Updated `PLEX_LD_LIBRARY_PATH` locations in config/readme.
