### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by dcplaya** [l3uddz/plex_autoscan#87]
When submitting the following path to the manual scan webpage, I get a Internal Server Error

```
/mnt/TVShows/Superstore/Season 4/Superstore - S04E17 - Quinceañera [WEBDL-1080p][EAC3 5.1][h264][NTb].mkv
```

The exact error is 
```
Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
```

Forgot to add, it actually added the path to the scan log. It just displayed the error for the webpage.

**Comment by desimaniac** [comment]
Maybe cause it is looking for paths and not specific filenames ?
