### ISSUE TITLE
ImportError: cannot import name GoogleDrive with Python2

### ISSUE THREAD

**Issue by desimaniac** [l3uddz/plex_autoscan#94]
@sabrsorensen @l3uddz @daghaian 

```
   File "/opt/plex_autoscan/scan.py", line 73, in <module>
     from google import GoogleDrive, GoogleDriveManager
 ImportError: cannot import name GoogleDrive
```

Any reason why this would be occurring randomly with python2 but resolves when you change the shebang to `#!/usr/bin/env python3`? If need be, we can switch them all to have that shebang.

**Comment by sabrsorensen** [comment]
I don't know why this would be cleared up by switching to Python 3, cursory googling shows this as a possible circular dependency but I couldn't see where that was the case. Would changing to `import google` possibly address the issue? I think google/__init__.py is already configured to import GoogleDrive and GoogleDriveManager into the same namespace as `from google import GoogleDrive, GoogleDriveManager`.

**Comment by desimaniac** [comment]
The user eventually uninstalled all pip packages and reinstalled python again and that seemed to have fixed it. Not sure how another package could have been an issue. I guess we can close this for now.

**Comment by n0rbertg** [comment]
Just a FYI, I've ran into this as well, and `import google` fixed it. 
Not sure which package caused it, I've upgraded Cloudbox and the OS as well (Ubuntu 18.04) and after Cloudbox upgrade plex_autoscan didn't start.
