### ISSUE TITLE
autoscan queue failing due to multiple requests

### ISSUE THREAD

**Issue by Qwatuz** [l3uddz/plex_autoscan#95]
I believe there is an issue with sqlite3 database having multiple requests to process at the same time, it tends to stop scanning anything in and will continue building the queue up.

If files are very slowly fed to autoscan, it will manage to process without jamming up in the queue.

**Comment by zenjabba** [comment]
I don't experience the same thing. I just tried pushing 40 TV shows into Plex_Autoscan and it grabbed each of them and started scanning.

**Comment by zenjabba** [comment]
I suggest you use `--loglevel DEBUG`and paste the last 30 lines
