### ISSUE TITLE
can i set scan root(not google drive root) folder?

### ISSUE THREAD

**Issue by Sagiamda** [l3uddz/plex_autoscan#97]
my process is
1. upload to google drive (another folder)
    move file to plexdrive mounted folder in google drive
2. upload to plexdrive mounted folder

(2) is run scanning...very well
but (1) is always ignore.
i think....
move process always ignore because this program watch google drive root.

so can i set watching folder?...
or other better then process...?

thanks for regards.

**Comment by desimaniac** [comment]
Read the readme. It's been updated. You need to specify specific paths under Allowed Paths.
